# Generated by Django 6.1 on 2026-08-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(help_text='Unique Process ID', unique=True)),
                ('name', models.CharField(help_text='Descriptive Process Name', max_length=120)),
                ('required_memory', models.IntegerField(help_text='RAM required in MB')),
                ('duration', models.IntegerField(help_text='Total execution time in seconds')),
                ('remaining_time', models.IntegerField(help_text='Remaining execution time in seconds')),
                ('status', models.CharField(choices=[('WAITING', 'En Espera'), ('RUNNING', 'En Ejecución'), ('COMPLETED', 'Completado'), ('TERMINATED', 'Terminado')], default='WAITING', max_length=20)),
                ('color', models.CharField(default='#3B82F6', max_length=15)),
                ('memory_start_address', models.IntegerField(blank=True, null=True)),
                ('memory_end_address', models.IntegerField(blank=True, null=True)),
                ('created_at_tick', models.IntegerField(default=0)),
                ('started_at_tick', models.IntegerField(blank=True, null=True)),
                ('finished_at_tick', models.IntegerField(blank=True, null=True)),
                ('queue_order', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['queue_order'],
            },
        ),
        migrations.CreateModel(
            name='SimulationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tick', models.IntegerField(default=0)),
                ('event_type', models.CharField(choices=[('INFO', 'Información'), ('PROCESS_CREATED', 'Proceso Creado'), ('PROCESS_ADMITTED', 'Asignado a Memoria'), ('PROCESS_QUEUED', 'En Cola de Espera'), ('PROCESS_FINISHED', 'Proceso Finalizado'), ('PROCESS_TERMINATED', 'Proceso Terminado'), ('MEMORY_FREED', 'Memoria Liberada')], default='INFO', max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SimulationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_memory', models.IntegerField(default=1024, help_text='Total RAM in MB (1 GB = 1024 MB)')),
                ('current_tick', models.IntegerField(default=0, help_text='Elapsed time in seconds (clock ticks)')),
                ('is_running', models.BooleanField(default=False, help_text='Whether auto-simulation is currently active')),
                ('speed_ms', models.IntegerField(default=1000, help_text='Auto-tick interval in ms')),
                ('algorithm', models.CharField(choices=[('FIRST_FIT', 'First Fit'), ('BEST_FIT', 'Best Fit'), ('WORST_FIT', 'Worst Fit')], default='FIRST_FIT', max_length=20)),
                ('last_pid', models.IntegerField(default=1000, help_text='Counter for generating unique PIDs')),
            ],
        ),
    ]
